# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'deneme_.ui'
#
# Created by: PyQt5 UI code generator 5.14.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Polaris(object):
    def setupUi(self, Polaris):
        Polaris.setObjectName("Polaris")
        Polaris.resize(683, 768)
        Polaris.setMinimumSize(QtCore.QSize(683, 384))
        Polaris.setMaximumSize(QtCore.QSize(1366, 768))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(252, 175, 62))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        Polaris.setPalette(palette)
        self.centralwidget = QtWidgets.QWidget(Polaris)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.tool_box = QtWidgets.QToolBox(self.centralwidget)
        self.tool_box.setMinimumSize(QtCore.QSize(680, 338))
        self.tool_box.setMaximumSize(QtCore.QSize(1336, 768))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        self.tool_box.setPalette(palette)
        self.tool_box.setAutoFillBackground(False)
        self.tool_box.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.tool_box.setObjectName("tool_box")
        self.Info_button = QtWidgets.QWidget()
        self.Info_button.setGeometry(QtCore.QRect(0, 0, 680, 650))
        self.Info_button.setObjectName("Info_button")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.Info_button)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.start_button = QtWidgets.QPushButton(self.Info_button)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.start_button.setFont(font)
        self.start_button.setAutoFillBackground(True)
        self.start_button.setObjectName("start_button")
        self.gridLayout_4.addWidget(self.start_button, 5, 0, 1, 1)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(6)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.Info_button)
        self.label_1.setEnabled(True)
        font = QtGui.QFont()
        font.setKerning(False)
        self.label_1.setFont(font)
        self.label_1.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_1.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_1.setMidLineWidth(0)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.Info_button)
        self.label_2.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.Info_button)
        self.label_3.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_5 = QtWidgets.QLabel(self.Info_button)
        self.label_5.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.Info_button)
        self.label_6.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.Info_button)
        self.label_7.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.label_9 = QtWidgets.QLabel(self.Info_button)
        self.label_9.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.label_8 = QtWidgets.QLabel(self.Info_button)
        self.label_8.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.label_4 = QtWidgets.QLabel(self.Info_button)
        self.label_4.setFrameShape(QtWidgets.QFrame.Panel)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.gridLayout_4.addLayout(self.verticalLayout, 3, 1, 1, 1)
        self.Kullamm_klavuzu = QtWidgets.QTextEdit(self.Info_button)
        self.Kullamm_klavuzu.setObjectName("Kullamm_klavuzu")
        self.gridLayout_4.addWidget(self.Kullamm_klavuzu, 3, 0, 1, 1)
        self.getting_info = QtWidgets.QLabel(self.Info_button)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        self.getting_info.setFont(font)
        self.getting_info.setObjectName("getting_info")
        self.gridLayout_4.addWidget(self.getting_info, 1, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_4, 0, 0, 1, 1)
        self.tool_box.addItem(self.Info_button, "")
        self.control_panel = QtWidgets.QWidget()
        self.control_panel.setGeometry(QtCore.QRect(0, 0, 680, 650))
        self.control_panel.setObjectName("control_panel")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.control_panel)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.upButton = QtWidgets.QPushButton(self.control_panel)
        self.upButton.setObjectName("upButton")
        self.gridLayout_2.addWidget(self.upButton, 0, 1, 1, 1)
        self.downButton = QtWidgets.QPushButton(self.control_panel)
        self.downButton.setObjectName("downButton")
        self.gridLayout_2.addWidget(self.downButton, 1, 1, 1, 1)
        self.leftButton = QtWidgets.QPushButton(self.control_panel)
        self.leftButton.setObjectName("leftButton")
        self.gridLayout_2.addWidget(self.leftButton, 1, 0, 1, 1)
        self.spaceButton = QtWidgets.QPushButton(self.control_panel)
        self.spaceButton.setObjectName("spaceButton")
        self.gridLayout_2.addWidget(self.spaceButton, 2, 0, 1, 3)
        self.rightButton = QtWidgets.QPushButton(self.control_panel)
        self.rightButton.setFocusPolicy(QtCore.Qt.StrongFocus)
        self.rightButton.setObjectName("rightButton")
        self.gridLayout_2.addWidget(self.rightButton, 1, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 2, 1, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.vel_panel = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.vel_panel.setFont(font)
        self.vel_panel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.vel_panel.setObjectName("vel_panel")
        self.verticalLayout_2.addWidget(self.vel_panel)
        self.vel_data = QtWidgets.QLabel(self.control_panel)
        self.vel_data.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.vel_data.setFrameShape(QtWidgets.QFrame.Box)
        self.vel_data.setScaledContents(False)
        self.vel_data.setAlignment(QtCore.Qt.AlignCenter)
        self.vel_data.setObjectName("vel_data")
        self.verticalLayout_2.addWidget(self.vel_data)
        self.sarj_panel = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sarj_panel.setFont(font)
        self.sarj_panel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.sarj_panel.setObjectName("sarj_panel")
        self.verticalLayout_2.addWidget(self.sarj_panel)
        self.sarj_data = QtWidgets.QLabel(self.control_panel)
        self.sarj_data.setFrameShape(QtWidgets.QFrame.Box)
        self.sarj_data.setAlignment(QtCore.Qt.AlignCenter)
        self.sarj_data.setObjectName("sarj_data")
        self.verticalLayout_2.addWidget(self.sarj_data)
        self.sicaklik_panel = QtWidgets.QLabel(self.control_panel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.sicaklik_panel.setFont(font)
        self.sicaklik_panel.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignHCenter)
        self.sicaklik_panel.setObjectName("sicaklik_panel")
        self.verticalLayout_2.addWidget(self.sicaklik_panel)
        self.sicaklik_data = QtWidgets.QLabel(self.control_panel)
        self.sicaklik_data.setFrameShape(QtWidgets.QFrame.Box)
        self.sicaklik_data.setAlignment(QtCore.Qt.AlignCenter)
        self.sicaklik_data.setObjectName("sicaklik_data")
        self.verticalLayout_2.addWidget(self.sicaklik_data)
        self.gridLayout_3.addLayout(self.verticalLayout_2, 1, 0, 1, 1)
        self.map_panel = QtWidgets.QLabel(self.control_panel)
        self.map_panel.setFrameShape(QtWidgets.QFrame.Panel)
        self.map_panel.setText("")
        self.map_panel.setPixmap(QtGui.QPixmap("../../../../../Downloads/map.png"))
        self.map_panel.setScaledContents(True)
        self.map_panel.setObjectName("map_panel")
        self.gridLayout_3.addWidget(self.map_panel, 1, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(self.control_panel)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.pushButton_2 = QtWidgets.QPushButton(self.control_panel)
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout.addWidget(self.pushButton_2)
        self.gridLayout_3.addLayout(self.horizontalLayout, 0, 1, 1, 1)
        self.gridLayout_6.addLayout(self.gridLayout_3, 0, 0, 1, 1)
        self.tool_box.addItem(self.control_panel, "")
        self.gridLayout.addWidget(self.tool_box, 0, 0, 1, 1)
        Polaris.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Polaris)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 683, 20))
        self.menubar.setObjectName("menubar")
        Polaris.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Polaris)
        self.statusbar.setObjectName("statusbar")
        Polaris.setStatusBar(self.statusbar)

        self.retranslateUi(Polaris)
        self.tool_box.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Polaris)

    def retranslateUi(self, Polaris):
        _translate = QtCore.QCoreApplication.translate
        Polaris.setWindowTitle(_translate("Polaris", "Kuzey Yıldızı "))
        self.start_button.setText(_translate("Polaris", "Start"))
        self.label_1.setText(_translate("Polaris", "Rasperry ile iletişim..."))
        self.label_2.setText(_translate("Polaris", "Arduino ile iletişim.........................................."))
        self.label_3.setText(_translate("Polaris", "Ros ile iletişim..."))
        self.label_5.setText(_translate("Polaris", "Serial bağlantılar"))
        self.label_6.setText(_translate("Polaris", "Raspi_server"))
        self.label_7.setText(_translate("Polaris", "Admin_client"))
        self.label_9.setText(_translate("Polaris", "Admin_server"))
        self.label_8.setText(_translate("Polaris", "Raspi_client"))
        self.label_4.setText(_translate("Polaris", "Tüm bağlantılar yapıldı..."))
        self.Kullamm_klavuzu.setHtml(_translate("Polaris", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'Ubuntu\'; font-size:9pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"center\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:20pt; font-weight:600;\">Kuzey Yıldızı</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Kuzey yılsızı hakkında genel bilgiler.  Nasıl çalıştığına dair</span></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">Arayüz hakkında bilgilernidrme </span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">hangi tuş ne işe yar.</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p>\n"
"<p style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:14pt;\">start ile sistemi başlat</span></p>\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px; font-size:14pt;\"><br /></p></body></html>"))
        self.getting_info.setText(_translate("Polaris", "Bilgilendirme"))
        self.tool_box.setItemText(self.tool_box.indexOf(self.Info_button), _translate("Polaris", "Info"))
        self.upButton.setText(_translate("Polaris", "Up"))
        self.downButton.setText(_translate("Polaris", "Down"))
        self.leftButton.setText(_translate("Polaris", "Left"))
        self.spaceButton.setText(_translate("Polaris", "Space"))
        self.rightButton.setText(_translate("Polaris", "Right"))
        self.vel_panel.setText(_translate("Polaris", "Hız (m/s)"))
        self.vel_data.setText(_translate("Polaris", "10"))
        self.sarj_panel.setText(_translate("Polaris", "Şarj Yüzdesi (%)"))
        self.sarj_data.setText(_translate("Polaris", "95"))
        self.sicaklik_panel.setText(_translate("Polaris", "Sıcaklık (C)"))
        self.sicaklik_data.setText(_translate("Polaris", "25"))
        self.pushButton.setText(_translate("Polaris", "Manuel"))
        self.pushButton_2.setText(_translate("Polaris", "Auto"))
        self.tool_box.setItemText(self.tool_box.indexOf(self.control_panel), _translate("Polaris", "Control Panel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Polaris = QtWidgets.QMainWindow()
    ui = Ui_Polaris()
    ui.setupUi(Polaris)
    Polaris.show()
    sys.exit(app.exec_())
